// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-09-14 15:02:04.333979889 +0800 CST m=+0.024598573

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/api/v1/admin/cert/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "添加证书",
                "parameters": [
                    {
                        "description": "证书详细信息",
                        "name": "certInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.C_certs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "certID 不需要填写, 失败返回 false 及 msg",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/cert/preview": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "预览证书",
                "parameters": [
                    {}
                ],
                "responses": {
                    "200": {
                        "description": "data:{\"image_save_url\":\"upload/images/96a.jpg\", \"image_url\": \"http://...\"}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/cert/upload_image": {
            "post": {
                "produces": [
                    "multipart/form-data"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data:{\"image_save_url\":\"upload/images/96a.jpg\", \"image_url\": \"http://...\"}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/certs": {
            "get": {
                "description": "查询所有证书列表",
                "produces": [
                    "application/json"
                ],
                "summary": "获取证书列表",
                "responses": {
                    "200": {
                        "description": "data:[{\"Id\":0, \"Name\":\"证书1\"}]",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/auth": {
            "get": {
                "summary": "登陆验证",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username for login",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The password for login",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\":{\"token\":string}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ResponseMsg": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.C_certs": {
            "type": "object",
            "properties": {
                "certID": {
                    "type": "integer"
                },
                "certName": {
                    "type": "string"
                },
                "certPrefix": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                },
                "imgName": {
                    "type": "string"
                },
                "positions": {
                    "type": "object",
                    "$ref": "#/definitions/models.position"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.coord": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            }
        },
        "models.position": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "object",
                    "$ref": "#/definitions/models.coord"
                },
                "englishName": {
                    "type": "object",
                    "$ref": "#/definitions/models.coord"
                },
                "name": {
                    "type": "object",
                    "$ref": "#/definitions/models.coord"
                },
                "personalID": {
                    "type": "object",
                    "$ref": "#/definitions/models.coord"
                },
                "serialNumber": {
                    "type": "object",
                    "$ref": "#/definitions/models.coord"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
