// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-09-13 18:24:28.432460597 +0800 CST m=+0.025158473

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/api/v1/admin/cert/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "添加证书",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"success\": bool,\"data\":[]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/cert/upload_image": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "上传图片",
                "parameters": [
                    {}
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"success\": bool,\"data\":{\"image_save_url\":\"upload/images/96a.jpg\", \"image_url\": \"http://...\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/certs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取证书列表",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"success\": bool,\"data\":[]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
