// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-09-21 11:41:36.773060308 +0800 CST m=+0.025874320

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/api/v1/admin/applicants/certs/{certid}": {
            "get": {
                "description": "查询指定证书的申领信息,",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "查询证书申领信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cert ID",
                        "name": "certid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "类型 all | export | verify | passed | Reject",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示的条数",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data:[{\"\"}]",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "导入审核结果",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cert ID",
                        "name": "certid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "审核结果.csv",
                        "name": "excel",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data:{\"\"}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/certs": {
            "get": {
                "description": "查询所有证书列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "获取证书列表",
                "responses": {
                    "200": {
                        "description": "data:[{\"cert_id\":\"0\", \"cert_name\":\"证书1\", \"status\":\"enable\"}]",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "添加证书",
                "parameters": [
                    {
                        "description": "证书详细信息",
                        "name": "certInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.C_certs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "certID 不需要填写, 失败返回 false 及 msg",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/files/applicants/certs/{certid}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "导出用户申领信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cert ID",
                        "name": "certid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类型 export | Reject",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data:{\"file_save_path\":\"upload/images/96a.csv\", \"file_url\": \"http://...\"}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/fonts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "查询字体列表",
                "responses": {
                    "200": {
                        "description": "data:{\"image_save_path\":\"upload/images/96a.jpg\", \"image_url\": \"http://...\"}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/images": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "上传证书模板",
                "parameters": [
                    {
                        "type": "file",
                        "description": "证书模板图片",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data:{\"image_save_path\":\"upload/images/96a.jpg\", \"image_url\": \"http://...\"}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/images/certs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "预览证书",
                "parameters": [
                    {
                        "description": "证书详细信息",
                        "name": "positions",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ImageDesigner"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data:{\"image_save_path\":\"upload/images/96a.jpg\", \"image_url\": \"http://...\"}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/v1/weixin/applicants": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户申请"
                ],
                "summary": "申请证书",
                "parameters": [
                    {
                        "description": "用户提交信息",
                        "name": "applicant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Applicant"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "cost 与 applyStatus 不提交. 失败返回 false 及 msg",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/auth": {
            "get": {
                "tags": [
                    "认证授权"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username for login",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The password for login",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\":{\"token\":string}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.ResponseMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ResponseMsg": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.Applicant": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cert_id": {
                    "type": "string"
                },
                "cert_name": {
                    "type": "string"
                },
                "cert_type": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "company_nature": {
                    "type": "string"
                },
                "company_scale": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "english_name": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "personal_id": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                },
                "province": {
                    "type": "string"
                },
                "study_date": {
                    "type": "string"
                },
                "wechat_id": {
                    "type": "string"
                }
            }
        },
        "models.C_certs": {
            "type": "object",
            "properties": {
                "authority": {
                    "type": "string"
                },
                "cert_id": {
                    "type": "integer"
                },
                "cert_name": {
                    "type": "string"
                },
                "image_design": {
                    "type": "object",
                    "$ref": "#/definitions/models.ImageDesigner"
                },
                "price": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.Coord": {
            "type": "object",
            "properties": {
                "font": {
                    "type": "string"
                },
                "font_size": {
                    "type": "number"
                },
                "str": {
                    "type": "string"
                },
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            }
        },
        "models.ImageDesigner": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "object",
                    "$ref": "#/definitions/models.Coord"
                },
                "english_name": {
                    "type": "object",
                    "$ref": "#/definitions/models.Coord"
                },
                "img_name": {
                    "type": "string"
                },
                "name": {
                    "type": "object",
                    "$ref": "#/definitions/models.Coord"
                },
                "personal_id": {
                    "type": "object",
                    "$ref": "#/definitions/models.Coord"
                },
                "serial_number": {
                    "type": "object",
                    "$ref": "#/definitions/models.Coord"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
